# Generated by Django 3.2.4 on 2021-06-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.DecimalField(decimal_places=4.0, max_digits=4)),
                ('nome_do_livro', models.TextField()),
                ('autores', models.TextField(default='Desconhecido')),
                ('situacao', models.BooleanField()),
                ('cadastro_em', models.DateTimeField(auto_now_add=True)),
                ('cadastrador_do_livro', models.TextField()),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('editor_do_livro', models.TextField()),
            ],
        ),
    ]
