# Generated by Django 3.2.4 on 2021-06-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livro',
            fields=[
                ('numero', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False, unique=True)),
                ('nome_do_livro', models.TextField()),
                ('autores', models.TextField(default='Desconhecido')),
                ('situacao', models.CharField(choices=[('Free', 'Disponível'), ('Unfree', 'Emprestado')], max_length=10)),
                ('cadastro_em', models.DateTimeField(auto_now_add=True)),
                ('cadastrador_do_livro', models.TextField()),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('editor_do_livro', models.TextField()),
            ],
        ),
    ]
